pom.xml

Updates the Spring Boot Version to 2.5.14 due to a CVE for one of its sub-dependencies in the previous version (spring-security-config:5.5.6)

update spring boot version to 2.5.14

---

backend/deployment/registry/LICENSE

Adds Apache 2.0 license file to Helm Chart since packaged version of the Helm Chart might be distributed individually without the rest of this repository.

add Apache 2.0 License file to Helm Chart

---

backend/deployment/registry/Chart.yaml
backend/deployment/registry/values.yaml

This commit adjusts the Helm chart version for the Digital Twin Registry to image app version 0.2.0-M1-multi-tenancy.

Update Helm chart version to 0.2.0

---

backend/deployment/registry/Chart.yaml
backend/deployment/registry/values.yaml

This commit adjusts the Helm chart version to 0.2.1 and appVersion 0.2.0-M2-multi-tenancy.

Adjust Helm chart version to 0.2.1

---

pom.xml

- increase springboot version to 2.7.5
- increase explicitly spring-security-core version to 5.7.5 to fix cve-2022-31692

Fix cve-2022-31692

---

pom.xml

Increase jackson-databind version to 2.14.0

fix cve-2022-42003 (jackson-databind)

---

.github/workflows/helm-release.yml

The new workflow releases the registry Helm chart using a separate branch and GitHub Pages.

Add new workflow for Helm chart releases

---

.github/workflows/helm-release.yml

Adjust the Helm chart release workflow for the registry to accept the workflow_dispatch event.

Adjust Helm chart release workflow to include workflow_dispatch trigger

---

charts/registry/Chart.lock

This fixes a bug in the Helm chart release workflow induced by the Chart.lock file.

Fix a bug in the Helm chart release workflow

---

pom.xml

Fix following CVEs:
* CVE-2022-41946 (Update org.postgresql:postgresql to version 42.5.1)
* CVE-2022-41854 (Update org.yaml:snakeyaml to version 1.32)

Fix CVEs (2022-41946 and CVE-2022-41854)

---

README.md

The paths in the README don't match the current structure in the main branch. If some modification has been made to the repo structure in another branch, maybe that needs to be merged with main. In any case, I propose here a fix for main.

Fix paths in README.md

---

AUTHORS.md
backend/src/main/java/org/eclipse/tractusx/semantics/ApiExceptionHandler.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/controller/AssetAdministrationShellApiDelegate.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/controller/SpecificAssetIdArrayConverter.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/controller/SpecificAssetIdConverter.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/mapper/ShellMapper.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/mapper/ShellMapperCustomization.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/mapper/SubmodelMapper.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/security/OAuthSecurityConfig.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AbstractAssetAdministrationShellApi.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiSecurityTest.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiTest.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/TestUtil.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/mapper/ShellMapperTest.java

Update of the code of the Digital Twin Registry to the new AAS Version 3.0.
We updated the Asset Administration Shell Registry API and the Asset Administration Shell Basic Discovery API.
We are aware that there are still some open issues that will be resolved until the next release.

Update of Digital Twin Registry to the AAS Version 3.0

---

charts/registry/Chart.yaml
charts/registry/templates/keycloak/database-credentials.yaml

This change disables the creation of the keycloak-database secret if keycloak is disabled at all
- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if you are unsure, who to contact, or if want to engage in a general discussion
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation contribution …

fix: Disable creation of keycloak-database secret if keycloak is disabled

---

backend/src/main/java/org/eclipse/tractusx/semantics/registry/controller/AssetAdministrationShellApiDelegate.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AbstractAssetAdministrationShellApi.java

feat:Removed TODOs and comments

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/semantics/registry/controller/AssetAdministrationShellApiDelegate.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/ShellRepository.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java
backend/src/main/resources/static/aas-registry-openapi.yaml
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiSecurityTest.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiTest.java
docs/README.md

Add deprecated function query. This is needed for the release 3.2

Add deprecated function query. This is needed for the release 3.2

---

.tractusx

The way of how the legal information is commented in .tractusx file has changed to yaml style (#) to get it handled in the dashboard.

legal header comment switched to yaml comment

---

backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/ShellRepository.java

This PR includes the query change for lookup API. It was observed that lookup API performance was very slow when number of records are more than 18K, this change will improve the performance of the lookup API

Lookup api query changed to improve performance

---

CHANGELOG.md
DEPENDENCIES
backend/pom.xml
pom.xml

Veracode CVEs fix in jetty-http jar.
- CVE-2023-36478 | CWE-190
Denial Of Service (DoS): org.eclipse.jetty is vulnerable to Denial Of Service (DoS). The vulnerability arises from the library's failure to appropriately limit the size in HPACK header values. This allows an attacker to repeatedly send maliciously crafted HTTP messages, leading to an integer overflow and ultimately causing an application crash through the `checkSize` function in `MetaDataBuilder.java`.
- CVE-2023-40167| CWE-130
HTTP Request Smuggling: Jetty is vulnerable to HTTP Request Smuggling. The vulnerability is due to accepting `+` character proceeding the content-length in the request. This vulnerability can be exploited by the attacker to possibly conduct request smuggling attacks.

fix:Veracode CVEs fix

---

.github/actions/generate-dependencies-notice/action.yml
.github/actions/generate-dependencies-notice/index.js
.github/workflows/build-snapshot.yml
.github/workflows/gitleaks.yml
.github/workflows/helm-test.yml
.github/workflows/release.yml
.github/workflows/trivy.yml
.github/workflows/veracode.yaml
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellAccessHandler.java

Legal information header has been corrected:
- the legal information header will start at line 1 in each class
- double copyright expression like "Copyright (c) 2023 Copyright (c) 2023" have been corrected

legal header information corrected

---

.github/workflows/trivy.yml

prepare trivy scan for not failing on high findings

---

CHANGELOG.md
backend/src/main/resources/db/changelog/db.changelog-v3.yaml
backend/src/main/resources/static/aas-registry-openapi.yaml

Increased the field length of column "Sub_Protocol_Body" from table "SUBMODEL_ENDPOINTSUBMODEL_ENDPOINT" to 2048. Also the openapi.yml has been adjusted to this value.

update column 'Sub_Protocol_Body' to length of 2048

---

backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/ShellRepository.java

Issue:
With a growing number of shells registered ShellRepository.findByIdExternalAndExternalSubjectId() has an exponentially growing run time when accessed by a different one than the owning tenant id.
Solution:
The fix replaces the expensive IN statement in the WHERE clause of the backing SQL command by a much more cheaper EXISTS statement.

fix: Runtime issue of ShellRepository.findByIdExternalAndExternalSubjectId()

---

backend/src/main/resources/static/aas-registry-openapi.yaml

fix:KICS Violation

---

CHANGELOG.md
INSTALL.md

authentication is set to 'true' in documentation to be in line with configutation.

set authentication to 'true' in documatation

---

backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/ShellIdentifierRepository.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/ShellRepository.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java

- Moves ShellRepository.findExternalShellIdsByIdentifiersByExactMatch to ShellIdentifierRepository
- Fixes service method listing all shells
Related to #287 

feat: Extend DTR APIs for Access management - Clean-up

---

charts/registry/Chart.yaml
charts/registry/templates/registry/registry-deployment.yaml
charts/registry/values.yaml

Make securityContext (pod and container) configurable

Make securityContext (pod and container) configurable

---

DEPENDENCIES
backend/pom.xml
pom.xml

Update Springboot to version 3.2.2 and use only jakarta 6.0.0

Update Springboot to version 3.2.2 and use only jakarta 6.0.0

---

backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiSecurityTest.java

- Partially reformats AssetAdministrationShellApiSecurityTest to prepare a bigger change
Note: Please review with ignored whitespaces to see that nothing changed
Updates #286

feat: Implementation of CRUD API for Access management APIs - Preparation 01

---

access-control-service-sql-impl/pom.xml
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/AccessRule.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/AccessRulePolicy.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/policy/PolicyOperator.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/validation/AccessRulePolicyValueValidator.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/validation/OnCreate.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/validation/OnUpdate.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/validation/ValidAccessRulePolicyValue.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/validation/ValidValidityPeriod.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/validation/ValidityPeriodValidator.java
access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/validation/AbstractValidationTest.java
access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/validation/AccessRulePolicyValidationTest.java
access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/validation/AccessRuleValidationTest.java
pom.xml

- Adds custom validator implementations
- Configures validation groups using JSR-303 annotations
- Adds tests to verify that validation is working
- Fixes internal logic of policy values to allow validation rules to enforce validation instead of runtime exceptions
Updates #286 

feat: Implementation of CRUD API for Access management APIs - Add rule validations

---

backend/src/test/java/org/eclipse/tractusx/semantics/registry/GranularAssetAdministrationShellApiSecurityTest.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/JwtTokenFactory.java

- Adds tests covering the access rule specific API
Updates #286 

feat: Implementation of CRUD API for Access management APIs - Access rule API tests

---

access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/AccessRule.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java
backend/src/main/resources/db/changelog/db.changelog-v4.yaml

- Fixes issues which were causing failures when using with PostgreSQL
Updates #286 

fix: Implementation of CRUD API for Access management APIs

---

charts/registry/Chart.yaml
charts/registry/values.yaml
docs/development/postman/README.md
docs/development/postman/tractusx-dtr-access-rule-management-api-v1.0-collection.json

Add postman collection for access rule management.
Adjust default wildcard types

Add postman collection for access rule management.

---

docs/README.md

Document granular access control
- Adds clarification about how granular access control works

Document granular access control

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/semantics/registry/controller/AssetAdministrationShellApiDelegate.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/mapper/ShellMapper.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java
backend/src/main/resources/static/aas-registry-openapi.yaml
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AbstractAssetAdministrationShellApi.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiTest.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/TestUtil.java
docs/development/postman/tractusx-dtr-aas-3.1.0-collection.json

New API POST lookup/shellsByAssetLink has been introduced to retrieve Shell IDs without using base 64 encoding.

Feat: Lookup API v3.1 POST Get Shell IDS

---

libraries/edc-extension/pom.xml
libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/AccessControlServiceException.java
libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlServiceExtension.java
libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/HttpAccessControlCheckClientConfig.java
libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/HttpAccessControlCheckDtrClientConfig.java
libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/client/DtrOauth2TokenClient.java
libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/client/Oauth2TokenClient.java
libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/HttpAccessControlCheckClientConfigTest.java
libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/HttpAccessControlCheckDtrClientConfigTest.java
libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/client/DtrOauth2TokenClientTest.java
pom.xml

- Creates new library for the granular access control extension
- Adds extension configuration
- Implements OAuth2 token client
Updates #352

EDC extension

---

CHANGELOG.md
DEPENDENCIES
access-control-service-interface/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/api/model/ShellVisibilityCriteria.java
access-control-service-interface/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/api/model/ShellVisibilityCriteriaTest.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/service/SqlBackedAccessControlRuleService.java
access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/service/SqlBackedAccessControlRuleServiceTest.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/GranularShellAccessHandler.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiSecurityTest.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/GranularAssetAdministrationShellApiSecurityTest.java
docs/README.md
pom.xml

Fixed behaviour of access rule management in case of multiple specificAssetIds with same keys and different values.

BugFix: Fixed behaviour of access rule management

---

CHANGELOG.md
backend/src/main/resources/static/aas-registry-openapi.yaml

Fixed regex pattern for specificAssetId value field

Fix: Fixed regex pattern for specificAssetId value field

---

.github/workflows/publish-edc-ext-to-maven-central.yml

Bugfix - Triggering Maven Central publish workflow

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/GranularShellAccessHandler.java

Bugfix access rule management for submodelfilter (visibleSemanticIds): Remove condition on `semanticId.keys.type = submodel` because the `semanticId.keys.type` should be `GlobalReference`. This check is not needed.

Bugfix access rule management for submodelfilter (visibleSemanticIds)

---

CHANGELOG.md
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/AccessRulePolicy.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/service/SqlBackedAccessControlRuleService.java
access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/service/SqlBackedAccessControlRuleServiceTest.java
access-control-service-sql-impl/src/test/resources/example-access-rules.json
access-control-service-sql-impl/src/test/resources/example-publicreadable-access-rules.json
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellAccessHandlerConfiguration.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/GranularAssetAdministrationShellApiSecurityTest.java

- Bugfix: Introduced wildcardAllowedTypes for access management rules. Now, specificAssetIds can only be defined as PUBLIC_READABLE if their types are included in the wildcardAllowedTypes list.

Bugfix: PUBLIC_READABLE only for defined wildcardAllowedTypes 

---

.github/workflows/publish-edc-ext-to-maven-central.yml
libraries/edc-extension/pom.xml
pom.xml

Move maven publish build to parent pom and add profile for publishing extension. This is needed to publish parent pom in maven too. 

Move maven publish build to parent pom

---

libraries/edc-extension/CHANGELOG.md
libraries/edc-extension/README.md
libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlConfigExtension.java
libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/client/DtrAccessVerificationClient.java

bugfix mixlower and uppercase for param definitions

bugfix mixlower and uppercase for param definitions

---

INSTALL.md

Add topic postgresql extension

Add topic postgresql extension

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/semantics/registry/controller/AssetAdministrationShellApiDelegate.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java
backend/src/main/resources/static/aas-registry-openapi.yaml
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiTest.java

Update AAS to v3.0.2_SSP-001

---

CHANGELOG.md
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/AccessRule.java

Bugfix accessRule: set updatable param to true for tenantTarget
-[Github Issue](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/489)

Bugfix accessRule: set updatable param to true for tenantTarget

---

.github/workflows/trufflehog.yml
.thignore
CHANGELOG.md
DEPENDENCIES
charts/registry/Chart.yaml
charts/registry/README.md
charts/registry/README.md.gotmpl
charts/registry/templates/registry/registry-ingress.yaml
charts/registry/values.yaml

Currently the ingress configuration has been constrained, leading to issues:
- prefix conflicts with strict admission hooks (nginx doesn't allow prefix + wildcard, now also on INT)
- tls-secret may not be overwritten manually
I provided changes:
- tls secret now can be passed through (allows two dtr in the same namespace)
- ingress can now also be used as ` implementationSpecific` for path `/`
- provided a go template for helm-docs
- updated changelog (we can discuss if patch or minor change)
` helm template . > dtr.yaml` 
checking the ingress resource
```ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: release-name-digital-twin-registry
annotations:
{}
labels:
helm.sh/chart: digital-twin-registry-0.7.1
app.kubernetes.io/name: digital-twin-registry …
```

Fix(Ingress): passthrough tls secret and allow non-prefix paths

---

CHANGELOG.md
backend/src/main/resources/static/aas-registry-openapi.yaml
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/1_post_shell/expected-response.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/1_post_shell/request.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/2_get_shell_by_id/expected-response.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/2_get_shell_by_id/request.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/3_update_shell/expected-response.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/3_update_shell/request.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/4_get_updated_shell/expected-response.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/4_get_updated_shell/request.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/5_delete_shell/expected-response.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/5_delete_shell/request.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/6_get_deleted_shell/expected-response.json
backend/src/test/resources/integrationtests/aas-registry-usecases/37_testCRUDShellWithLongSubProtocolBodyWithinSpecs/6_get_deleted_shell/request.json
backend/src/test/resources/integrationtests/aas-registry-usecases/38_testCreateShellWithTooLongSubProtocolBodyOutsideSpecs/1_post_shell/expected-response.json
backend/src/test/resources/integrationtests/aas-registry-usecases/38_testCreateShellWithTooLongSubProtocolBodyOutsideSpecs/1_post_shell/request.json

Increased subprotocolbody limit back to 2048, see issue #522

fix: #522 subprotocolbody limited to 128 characters

---

CHANGELOG.md
access-control-service-interface/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/api/AccessControlRuleService.java
access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/service/SqlBackedAccessControlRuleService.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/ShellRepository.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/GranularShellAccessHandler.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java
backend/src/main/java/org/eclipse/tractusx/semantics/registry/utils/ShellSpecification.java

This pull request introduces enhancements to pagination, access control, and query optimization within the registry service. Key changes include the addition of granular access control filtering, improvements to pagination queries, and the introduction of new methods for managing access rules and associations.
* Added a new method `findAllByBpnWithinValidityPeriod` in `AccessControlRuleService` to retrieve mandatory specific asset IDs for a given BPN within a validity period. [[1]](diffhunk://#diff-46b02c107cec27f5b05e7aba736ff1edc372f4fa03f451d671a3c68c0f5c8a72R42-R43) [[2]](diffhunk://#diff-e61b2e56cca0882018162217866c8210588134d39d6ed678eb546eff5e4bb743R174-R192)
* Introduced granular access control in `ShellService`, including a feature to filter results based on mandatory specific …

fix: high number of select statements

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/semantics/registry/security/OAuthSecurityConfig.java
backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiSecurityTest.java

Fixes #553 by adding a matcher to cover the "POST /lookup/shellsByAssetLink" endpoint.

feat: add matcher for shellsByAssetLink endpoint
