eclipse-tractusx/sldt-digital-twin-registry

- .github/workflows/gitleaks.yml
Signed-off-by: Johannes Kristan <johannes.kristan@bosch.io>
> Add GitHub action to check for Secrets

- backend/Dockerfile
- backend/pom.xml
Align the artifact-id assigned in the pom.xml and used in the Dockerfile for the backend.
> align artifact-id for the backend

- pom.xml
Update the Spring Version in response to the findings in https://avd.aquasec.com/nvd/2022/cve-2022-22965/.
> update spring version to 5.3.20

- .github/workflows/gitleaks.yml
- README.md
- backend/Dockerfile
- backend/pom.xml
- backend/postgres/docker-compose.yml
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/ShellRepository.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/security/LocalOauthSecurityConfig.java
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application.yml
- pom.xml
- Upgrade Spring Boot to 2.7.3.
- Introduce docker-compose file with postgres for local test execution and development if needed
> Upgrade Spring Boot to Version 2.7.3

- backend/pom.xml
- pom.xml
Temporary fix for a finding in snakeyaml 1.30
> Adjust snakeyaml version to 1.31

- backend/src/main/resources/static/aas-registry-openapi.yaml
This PR fixes findings of the KICS scan where the array maxItems property was not set.
> Adjust openapi spec to fix KICS findings

- README.md
- backend/deployment/registry/values.yaml
- value.yaml (Adjust port cause springboot app runs on 4243)
> Adjust value.yaml and README.md (setup)

- backend/deployment/registry/Chart.yaml
Increase chart version from 0.2.2 to 0.2.3
> Update chart version to 0.2.3

- .github/workflows/build-snapshot.yml
This PR adjusts the workflow for testing and building the DTR to also run on PRs.
> Adjust Snapshot Build workflow

- backend/deployment/registry/Chart.yaml
- backend/deployment/registry/values.yaml
These changes upgrade the registry Helm chart to version 0.2.4 and increases the appVersion to 0.2.0-M4-multi-tenancy.
> Update Helm chart to version 0.2.4

- backend/src/main/resources/static/aas-registry-openapi.yaml
* Change content of title and description
> Update title and description of aas-registry-openapi.yaml

- charts/registry/Chart.yaml
- charts/registry/templates/registry/registry-deployment.yaml
- charts/registry/values.yaml
Adjust chart configuration (deployment.yaml and value.yaml):
* Split value for image into image registry, repository and version.
* Introduce appVersion as default
> Making image version configurable and introduce appVersion as default

- charts/registry/Chart.yaml
- pom.xml
Increase springboot version to 3.0.5 to solve the vulnerability spring-expression
> Fix vulnerability spring-expression

- CHANGELOG.md
- charts/registry/Chart.yaml
Increase helm version to 0.2.11
Increase appVersion to 0.2.0-M8-multi-tenancy
Add changelog for 0.2.0-M8-multi-tenancy
> Prepare helm release 0.2.10

- backend/Dockerfile
- charts/registry/Chart.yaml
- charts/registry/templates/registry/registry-deployment.yaml
> Add user id for non-root user spring

- CHANGELOG.md
- charts/registry/Chart.yaml
Increase helm to version 0.2.12
Increase image version to 0.2.0-M9-multi-tenancy
> Prepare release 0.2.12

- CHANGELOG.md
- charts/registry/Chart.yaml
- charts/registry/templates/registry/registry-deployment.yaml
- charts/registry/templates/registry/registry-ingress.yaml
- charts/registry/templates/registry/registry-secret.yaml
- charts/registry/templates/registry/registry-service.yaml
- charts/registry/values.yaml
* Increase helm version to 0.2.16
* Increase image to 0.2.0-M11-multi-tenancy
* Update license Header
> Prepare release 0.2.15

- .tractusx
> Add .tractusx file

- CHANGELOG.md
Add 0.2.0-M12-multi-tenancy in changelog.md
> Add 0.2.0-M12-multi-tenancy changelog

- CHANGELOG.md
- charts/registry/Chart.yaml
- pom.xml
* Prepare decentral DTR in veresion 0.3.1-M1
* fix CVEs (update springboot to version 3.1.0)
> Prepare decentral DTR in version 0.3.1-M1

- CHANGELOG.md
- charts/registry/Chart.yaml
* Increase version to 0.3.2-M1
* Fix CVE-2023-20862
* FIX CVE-2023-20873
> Prepare dDTR in version 0.3.2-M1

- .github/workflows/veracode-scan.yml
* add new github action for veracode-scan via tractusx
> Add veracode-scan for digital twin registry

- charts/registry/Chart.yaml
- charts/registry/values.yaml
* Update Chart version to 0.3.3 and appversion to 0.3.3-M1
* Adjust repository to get the image from dockerhub
> feat:Prepare helm release 0.3.3

- charts/registry/Chart.yaml
Prepare helm version 0.3.5. with appversion 0.3.4-M1
> feat: Prepare helm version 0.3.5

- backend/src/main/resources/static/aas-registry-openapi.yaml
This feature includes the preparation of updating the APIs to the AAS Version 3.0
* Update the aas-registry-openapi.yml to the newest aas Version 3.0
> feat:Prepare new AAS API in version 3.0 (Update openapi.yml)

- backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiTest.java
Enable Shell API test for new version AAS 3.0
> feat: Adjustment to Shell Api test for new AAS 3.0 API

- backend/src/main/resources/static/aas-registry-openapi.yaml
- charts/registry/templates/tests/test-connection.yaml
Fixed KICS high violations.
Fixes
- Privilege Escalation Allowed.
- Array without Maximum Number of Items.
- Global Security Field Is Undefined (v3).
- Field 'securityScheme' On Components Is Undefined.
> bug:kics high findings

- CHANGELOG.md
- backend/src/main/resources/db/changelog/db.changelog-master.yaml
- backend/src/main/resources/db/changelog/db.changelog-v2.yaml
Length of column 'SUB_PROTOCOL_BODY' is changed from 50 char to 2000 char in table 'SUBMODEL_ENDPOINT'.
> Bug: Modified column SubProtocolBody length in table SUBMODEL_ENDPOINT

- charts/registry/Chart.yaml
Increase helm version from 0.3.6 to 0.3.7.
Increase Image version from 0.3.5-M1 to 0.3.6-M1
> Prepare Helm release version 0.3.7

- CHANGELOG.md
- backend/src/main/resources/static/aas-registry-openapi.yaml
Adjustment done in openapiyml for subprotolbody field length.
Adjusted Changelog file for new version 0.3.7-M1
> Bugfix: Adjustment done in openapiyml for subprotolbody field length

- charts/registry/Chart.yaml
changes done for helm release to version 0.3.8 and app version 0.3.7-M1.
> Feat:changes done for helm release to version 0.3.8 and app version 0.3.7-M1.

- CHANGELOG.md
- charts/registry/Chart.yaml
Prepare release for multi-tenancy in version 0.2.18 and image version 0.2.0-M13-multi-tenancy
> Prepare release for multi-tenancy in version 0.2.18

- backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/ShellRepository.java
- backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiSecurityTest.java
Fix functionality of specificAssetId visibility also for the lookup shell endpoints
> Fix functionality of specificAssetId visibility also for the lookup shell endpoints

- CHANGELOG.md
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/mapper/SubmodelMapper.java
Fix done for getting SemanticID in Submodel response. This is temporary solution for now.
> Bug: Fix done for getting SemanticID in Submodel response

- CHANGELOG.md
- charts/registry/Chart.yaml
- charts/registry/values.yaml
Preparation for helm release 0.3.9 and app version 0.3.8-M1.
Update changelog.md
> Feat: preparation for helm release 0.3.9 and app version 0.3.8-M1

- charts/registry/Chart.yaml
preparation for new helm release 0.3.10 and app version 0.3.9-M1
> Feat: preparation for new helm release 0.3.10 and app version 0.3.9-M1

- .github/workflows/helm-test.yml
- charts/registry/templates/tests/test-connection.yaml
- charts/registry/templates/tests/test-script-configmap.yaml
Fix helm test (automated api call tests) to use new api AAS 3
> fix: Fix helm test (automated api tests) to use new AAS 3 API

- charts/registry/Chart.yaml
- charts/registry/templates/tests/test-script-configmap.yaml
Prepared helm release version 0.3.11 and app version 0.3.10-M1.
> Feat: Prepared helm release version 0.3.11 and app version 0.3.10-M1

- CHANGELOG.md
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/utils/ShellSpecification.java
Resolved submodel sorting error while fetching
> Bug: Resolved submodel sorting error while fetching

- DEPENDENCIES
> Update DEPENDENCIES File

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
- Fix CVE-2023-34035 (update springboot to version 3.1.2)
- Fix CVE-2023-2976 (update google guava to version 32.1.1-jre)
> fix: CVE-2023-34035 and CVE-2023-2976

- charts/registry/Chart.yaml
Prepare helm release 0.3.14 with DTR image 0.3.12-M1
> Prepare helm release 0.3.14 with DTR image 0.3.12-M1

- backend/src/main/resources/static/aas-registry-openapi.yaml
- Fixed KICS violation - Array Items Has No Type (v3) - Schema array items type should be defined
> fix:Fixed KICS violations

- INSTALL.md
- charts/registry/.helmignore
- charts/registry/Chart.yaml
- charts/registry/README.md
Updated the readme file within the charts directory and some changes in .helmignore and chart.yaml have been made
> updated readme file in helm charts

- charts/registry/Chart.yaml
- charts/registry/values.yaml
Resource management setting have been adjusted.
> Resources mangement adjusted

- .tractusx
Corrected the LEADING_PRODUCT_REPOSITORY_URL
> feat:Corrected LEADING_PRODUCT_REPOSITORY_URL

- charts/registry/Chart.yaml
- charts/registry/values.yaml
Improved value for the cpu request in the values.yml
> Improved value for cpu request

- CHANGELOG.md
Prepare changelog version 0.3.13-M1
> Prepare changelog version 0.3.13-M1

- charts/registry/Chart.yaml
- charts/registry/templates/tests/test-script-configmap.yaml
Prepare release 0.3.20 and appversion 0.3.13-M1
> Prepare release 0.3.20 and appversion 0.3.13-M1

- docs/development/postman/README.md
Added legal notice statements in README.md file
> Feat: Added legal notice

- docs/README.md
Add documentation for access control of shells
> documentation for access control of shells

- charts/registry/Chart.yaml
Prepare helm version 0.3.22 and image 0.3.14-M1
> Prepare helm version 0.3.22 and image 0.3.14-M1

- charts/registry/Chart.yaml
Prepare helm release 0.3.23 and image version 0.3.15-M1
> Prepare helm release 0.3.23 and image version 0.3.15-M1

- CHANGELOG.md
change comment style in .tractusx to yaml style (#)
> adjust change to new image version 0.3.16-M1

- charts/registry/Chart.yaml
Prepare helm release 0.3.24 and image version 0.3.16-M1
> Prepare helm release 0.3.24 and image version 0.3.16-M1

- backend/loadtests/README.md
- backend/loadtests/docker-compose.yml
- backend/loadtests/locust/locustfile.py
Adjustment of locust test to handle AAS 3.0 API
> Adjustment of locust test to handle AAS 3.0 API

- backend/src/main/resources/db/changelog/db.changelog-master.yaml
- backend/src/main/resources/db/changelog/db.changelog-v3.yaml
The length of some nvarchars fields in the db have been increased.
> Adjust length of db fields

- pom.xml
Fix for [CVE-2022-45868](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45868)
> feat:Fix for CVE-2022-45868

- backend/src/main/resources/static/aas-registry-openapi.yaml
- backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiTest.java
Regex patterns have been implemented for input fields in APIs
> Feat: Implemented regex patterns for input fields in APIs

- charts/registry/Chart.yaml
Updated helm version to 0.3.25 and image version to 0.3.17
> prepare-release-0.3.25

- docs/README.md
Add data flow diagram from security assessment.
> docs: add dfd

- CHANGELOG.md
- charts/registry/Chart.yaml
- Update PostgreSQL version to 15.4
> feat:Update PostgreSQL version to 15.4

- charts/registry/Chart.yaml
Description
Prepare helm release 0.3.27 with image 0.3.19
> Prepare helm release 0.3.27 with image 0.3.19

- .github/workflows/aas-registry-e2e-test.yml
- e2e-tests/aas-registry/common.yaml
- e2e-tests/aas-registry/stage_auth.yaml
- e2e-tests/aas-registry/test_api.tavern.yaml
- e2e-tests/requirements.txt
* Introduce e2eTests for DTR
* Add github actions to trigger the e2eTests
> Introduce e2eTests for DTR

- .github/workflows/aas-registry-e2e-test.yml
- e2e-tests/aas-registry/common.yaml
- e2e-tests/aas-registry/test_api.tavern.yaml
> Fix failed e2e Tests.

- CHANGELOG.md
- backend/src/main/resources/static/aas-registry-openapi.yaml
- backend/src/test/java/org/eclipse/tractusx/semantics/registry/AbstractAssetAdministrationShellApi.java
- Fixed Open api specification by adding the context root.
> fix:Fixed Open api specification by adding the context root 

- backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiTest.java
Some test cases have been refactored to cover the test cases better.
> Testcases refactored

- SECURITY.md
SECURITY.md updated to newer version
fixes #252
> SECURITY.md updated to newer version

- .github/workflows/trivy.yml
Code clean up for comment old code in respect of trivy scan failure
> deleted comment outdated code in respect of trivy scan failure

- charts/registry/Chart.yaml
Rename chart name to digital-twin-registry
> Rename chart name to digital-twin-registry

- backend/src/main/java/org/eclipse/tractusx/semantics/registry/security/OAuthSecurityConfig.java
> feat:corrected deprecated usages

- CHANGELOG.md
Adjust changelog md to release 0.3.20
> Adjust changelog md to release 0.3.20

- charts/registry/Chart.yaml
Feature/prepare helm release 0.3.28
> Feature/prepare helm release 0.3.28

- CHANGELOG.md
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/security/OAuthSecurityConfig.java
Fixed handling of Oauth (Bearer token).
> Fixed handling of Oauth (Bearer token)

- CHANGELOG.md
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/security/OAuthSecurityConfig.java
Revert changes for handling Oauth
> Revert changes for handling Oauth

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
fixes found findings for CVE-2023-34053, CVE-2023-6378
> fixes findings for CVE-2023-34053, CVE-2023-6378

- charts/registry/Chart.yaml
Prepare new helm release 0.3.29 with image 0.3.21
> Prepare new helm release 0.3.29 with image 0.3.21

- backend/src/main/resources/static/aas-registry-openapi.yaml
> fix:KICS violation

- charts/registry/Chart.yaml
Updated helm version to 0.3.30 and image version to 0.3.22
> prepare-release-0.3.30

- charts/registry/Chart.yaml
prepare helm release 0.3.31 with image 0.3.23
> prepare helm release 0.3.31 with image 0.3.23

- charts/registry/Chart.yaml
Prepare helm release 0.4.0 includes 0.3.23
> Prepare helm release 0.4.0 includes 0.3.23

- .github/workflows/hotfix-helm-release.yml
Introduce helm release from Branch (for release 2024.03)
> Introduce helm release from Branch (for release 2024.03)

- .github/workflows/hotfix-release.yml
Introduce hotfix-release github action from branch for release-2024.03
> Introduce hotfix-release github action from branch for release-2024.03

- .github/workflows/helm-test.yml
- charts/registry/Chart.yaml
- charts/registry/templates/registry/postgres-init.yaml
- charts/registry/templates/registry/registry-deployment.yaml
- charts/registry/templates/registry/registry-secret.yaml
- charts/registry/values.yaml
Add autogenerate password secret for postgresql if not set
> Add autogenerate password secret for postgresql if not set

- AUTHORS.md
- access-control-service-interface/pom.xml
- access-control-service-interface/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/api/AccessControlRuleService.java
- access-control-service-interface/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/api/exception/DenyAccessException.java
- access-control-service-interface/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/api/model/AccessRule.java
- access-control-service-interface/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/api/model/ShellVisibilityCriteria.java
- access-control-service-interface/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/api/model/SpecificAssetId.java
- backend/pom.xml
- pom.xml
- Adds new module to provide service contract for access control rules as part of the new Access management feature
> feat: Extend DTR APIs for Access management - Add service interface

- access-control-service-sql-impl/pom.xml
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/exception/JsonConversionException.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/AccessRule.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/AccessRulePolicy.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/converter/AccessRulePolicyConverter.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/policy/AccessRulePolicyValue.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/policy/PolicyOperator.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/repository/AccessControlRuleRepository.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/repository/FileBasedAccessControlRuleRepository.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/service/SqlBackedAccessControlRuleService.java
- access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/repository/FileBasedAccessControlRuleRepositoryTest.java
- access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/service/SqlBackedAccessControlRuleServiceTest.java
- access-control-service-sql-impl/src/test/resources/example-access-rules.json
- backend/pom.xml
- pom.xml
- Adds new module to implement service contract for access control rules
- Adds new tests for the service and repository implementations
> feat: Extend DTR APIs for Access management - Add local file implementation of the service

- backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/ShellIdentifierRepository.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/ShellRepository.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/repository/SubmodelRepository.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/EntityNotFoundException.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellAccessHandler.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java
- Reformat and rearrange Repository and Service classes to prepare for a larger change
> chore: Code style changes

- access-control-service-sql-impl/pom.xml
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/AccessRule.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/AccessRulePolicy.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/converter/AccessRulePolicyConverter.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/repository/AccessControlRuleRepository.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/repository/FileBasedAccessControlRuleRepository.java
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/service/SqlBackedAccessControlRuleService.java
- access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/AccessRulePolicyTest.java
- access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/model/converter/AccessRulePolicyConverterTest.java
- access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/repository/FileBasedAccessControlRuleRepositoryTest.java
- access-control-service-sql-impl/src/test/java/org/eclipse/tractusx/semantics/accesscontrol/sql/service/SqlBackedAccessControlRuleServiceTest.java
- access-control-service-sql-impl/src/test/resources/example-access-rules.json
- Adds optional validity periods (validFrom and validTo) to access rules
- Implements the validity based filtering in the access rule repository
> feat: Extend DTR APIs for Access management - Add validity periods

- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/repository/FileBasedAccessControlRuleRepository.java
- backend/src/main/java/org/eclipse/tractusx/semantics/RegistryProperties.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/controller/AssetAdministrationShellApiDelegate.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/DefaultShellAccessHandler.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/GranularShellAccessHandler.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellAccessHandler.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellAccessHandlerConfiguration.java
- backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application.yml
- backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiSecurityTest.java
- backend/src/test/java/org/eclipse/tractusx/semantics/registry/GranularAssetAdministrationShellApiSecurityTest.java
- backend/src/test/resources/application-granular.yml
- backend/src/test/resources/application-test.yml
- backend/src/test/resources/test-access-rules.json
- Integrate Granular access control into DTR service calls
- Adds some basic access control tests
> feat: Extend DTR APIs for Access management - Implement granular access handling strategy

- backend/src/test/java/org/eclipse/tractusx/semantics/registry/AssetAdministrationShellApiSecurityTest.java
- backend/src/test/java/org/eclipse/tractusx/semantics/registry/GranularAssetAdministrationShellApiSecurityTest.java
- Reformats AssetAdministrationShellApiSecurityTest
- Reformats GranularAssetAdministrationShellApiSecurityTest
Updates #286 
> feat: Implementation of CRUD API for Access management APIs - Preparation 02

- access-control-service-sql-impl/pom.xml
- access-control-service-sql-impl/src/main/java/org/eclipse/tractusx/semantics/accesscontrol/sql/controller/AccessControlApiDelegate.java
- access-control-service-sql-impl/src/main/resources/static/access-control-openapi.yaml
- access-control-service-sql-impl/src/main/resources/static/access-control-openapi_schemas.yaml
- Adds CRUD API definition
- Adds new dependencies to allow CRUD API implementation
- Adds and configures OpenAPI plugin to generate API skeleton
Updates #286 
> feat: Implementation of CRUD API for Access management APIs - Generate CRUD API skeleton

- .github/workflows/publish-image-registry.yml
- DOCKER_NOTICE.md
- README.md
Separate notice file for docker hub
> Separate notice file for docker hub

- charts/registry/Chart.yaml
- charts/registry/templates/registry/registry-deployment.yaml
Add condition to deployment.yml if postgres enabled /add secret
> Add condition to deployment.yml if postgres enabled /add secret

- backend/postgres/docker-compose.yml
- backend/src/main/resources/db/changelog/db.changelog-v4.yaml
Remove ordered from sequence (liquibase) because it is not support in postgres.
> Remove ordered from sequence (liquibase)

- access-control-service-interface/pom.xml
- access-control-service-sql-impl/pom.xml
revert reference version to parent pom (DEV-SNAPSHOT)
> revert reference version to parent pom (DEV-SNAPSHOT)

- CHANGELOG.md
- charts/registry/Chart.yaml
> Prepeare Release 0.4.9-RC1

- charts/registry/Chart.yaml
> Prepare helm 0.4.9-RC2

- charts/registry/Chart.yaml
- charts/registry/templates/tests/test-script-configmap.yaml
Helm release 0.4.9
App version 0.4.1
> Feat: Helm release v0.4.9

- DEPENDENCIES
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/client/DtrAccessVerificationClient.java
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/client/DtrAccessVerificationRequest.java
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/client/HttpAccessVerificationClient.java
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/client/RequestKey.java
- libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/client/DtrAccessVerificationClientTest.java
- libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/client/DtrAccessVerificationRequestTest.java
- pom.xml
- Implements DTR authorization client
- Update dependencies
Updates #352
> EDC extension

- CHANGELOG.md
- access-control-service-sql-impl/src/main/resources/static/access-control-openapi.yaml
- backend/src/main/resources/static/aas-registry-openapi.yaml
> Fix: KICS findings fixed

- e2e-tests/aas-registry/test_api.tavern.yaml
Updated test script with correct response
> Fix: Updated test script

- e2e-tests/aas-registry/test_api.tavern.yaml
> Fix:Updated test script

- libraries/edc-extension/pom.xml
Fix release build for new module.
> Fix release build for new module.

- libraries/edc-extension/pom.xml
> revert new module fix

- CHANGELOG.md
- e2e-tests/aas-registry/common.yaml
- e2e-tests/aas-registry/stage_auth.yaml
- e2e-tests/aas-registry/test_api.tavern.yaml
fix changelog and adjust license header
> fix changelog and adjust license header

- DEPENDENCIES
- docs/EDC-extension-configuration.md
- docs/README.md
- libraries/edc-extension/pom.xml
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlConfigExtension.java
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlService.java
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlServiceExtension.java
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/HttpAccessControlCheckClientConfig.java
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/HttpAccessControlCheckDtrClientConfig.java
- libraries/edc-extension/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlConfigExtensionTest.java
- libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlServiceExtensionTest.java
- libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlServiceTest.java
- libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/HttpAccessControlCheckClientConfigTest.java
- libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/HttpAccessControlCheckDtrClientConfigTest.java
- pom.xml
- Adds extension class and metadata
- Defines new test cases
- Updates dependencies
Updates #352
> feat: EDC extension - Configure/init the extension

- .github/workflows/hotfix-release.yml
- .github/workflows/publish-edc-ext-to-maven-central.yml
- .github/workflows/release.yml
- libraries/edc-extension/pom.xml
- pom.xml
- Adds plugin configurations
- Includes the LICENSE, NOTICE and DEPENDENCIES files in the jar
- Defines required project properties for the EDC module
- Adds Distribution management for both GitHub and OSSRH
- Defines new workflow to publish artifact to Maven Central
- Adds triggers to the existing release workflows
Updates #352
> feat: EDC extension - Maven Central publish

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
Fix: Security fix spring-web:6.1.5.jar
> Fix: Security fix spring-web:6.1.5

- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlService.java
- libraries/edc-extension/src/test/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlServiceTest.java
- Swap parameters of the DtrDataPlaneAccessControlService
Updates #352
> EDC extension - Update due to EDC changes

- charts/registry/Chart.yaml
Helm release 0.4.11
app version 0.4.3
> Feat: Helm release 0.4.11

- docs/development/postman/tractusx-dtr-aas-3.1.0-collection.json
Adjust postman collection for aas 3
> Adjust postman collection for aas 3

- libraries/edc-extension/CHANGELOG.md
- libraries/edc-extension/README.md
Add Changelog for edc-extension
> Add Changelog for edc-extension

- backend/pom.xml
Bug Fix: Added new license_non-code to pom resources
> Fix: added new license to pom resources

- libraries/edc-extension/README.md
Add documentation for edc-extension usage
> Add documentation for edc-extension usage

- .github/workflows/publish-image-registry.yml
- backend/Dockerfile
- backend/pom.xml
Fixing broken pipe line issue after adding mandatory new licenses
> Fix: Removed licenses step from action

- CHANGELOG.md
- libraries/edc-extension/CHANGELOG.md
- libraries/edc-extension/README.md
Prepare for release 0.5.0 and edc-extension 0.1.0
> Prepare for release 0.5.0 and edc-extension 0.1.0

- .github/workflows/trivy.yml
Adjust trivy scan workflow (exit 1)
> Adjust trivy scan workflow (exit 1)

- .github/workflows/trivy.yml
> Fix trivy scan yaml

- charts/registry/Chart.yaml
> Prepare helm release 0.5.1

- docs/EDC-extension-configuration.md
- libraries/edc-extension/README.md
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlConfigExtension.java
- libraries/edc-extension/src/main/java/org/eclipse/tractusx/semantics/edc/dataplane/http/accesscontrol/DtrDataPlaneAccessControlServiceExtension.java
- clientSecret to client.secret
- clientId to client.id
Fix Property keys for clientSecret and clientId
> Fix Property keys for clientSecret and clientId

- charts/registry/Chart.yaml
- charts/registry/README.md
- charts/registry/templates/registry/registry-deployment.yaml
- charts/registry/values.yaml
Add readOnlyRootFilesystem to securitry context
> Add readOnlyRootFilesystem to securitry context

- .tractusx
TRG: 1.08. Added swagger path to .tractusx file
> Fix: Added swagger path to .tractusx file

- backend/DOCKER_NOTICE.md
Removed catenax-ng reference
closes #460
> BugFix: Removed catenax-ng reference

- .github/workflows/trivy.yml
Increase versions in trivy scan
> Increase versions in trivy scan

- pom.xml
Update springboot / lombok to the newest version
> Update springboot / lombok to the newest version

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
prepare release 0.6.0
Introduce dash license check in maven
> prepare release 0.6.0

- charts/registry/Chart.yaml
- charts/registry/README.md
> Prepare helm release 0.6.0

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
> Update Springboot to 3.3.5

- charts/registry/Chart.yaml
- charts/registry/README.md
> Update helm to version 0.6.1

- backend/src/test/resources/integrationtests/aas-registry-usecases/3_testCreateShellWithExistingIdExpectBadRequest/1_post_shell/expected-response.json
- backend/src/test/resources/integrationtests/aas-registry-usecases/3_testCreateShellWithExistingIdExpectBadRequest/1_post_shell/request.json
- docs/guideline-aws-cognito-configuration.md
* Fix integrationstest to resolve dependencies between testcases.
* Fix dct url
> Fix integrationstest to resolve dependencies between testcases / dct url doc

- .github/workflows/aas-registry-e2e-test.yml
- .github/workflows/build-snapshot.yml
- .github/workflows/gitleaks.yml
- .github/workflows/helm-release.yml
- .github/workflows/helm-test.yml
- .github/workflows/hotfix-helm-release.yml
- .github/workflows/hotfix-release.yml
- .github/workflows/kics.yml
- .github/workflows/publish-edc-ext-to-maven-central.yml
- .github/workflows/publish-image-registry.yml
- .github/workflows/release.yml
- .github/workflows/trivy.yml
- .github/workflows/veracode.yaml
Update github workflow dependencies
> Update github workflow dependencies

- charts/registry/Chart.yaml
- charts/registry/README.md
Helm release 0.7.2
App version 0.7.1
> Prepare Helm release 0.7.2

- CHANGELOG.md
- DEPENDENCIES
- backend/pom.xml
- pom.xml
- fixed security issue spring-security-crypto. upgraded to 6.3.8
- fixed security issue spring-boot version. upgraded to 3.3.11
> Fix: security issues spring boot

- charts/registry/Chart.yaml
- charts/registry/README.md
Helm version 0.8.0-RC1
App version 0.8.0-RC1
> Prep: Helm release 0.8.0-RC1

- CHANGELOG.md
> Update: Changelog updated

- .github/workflows/sonar-scan.yaml
> removed sonar scan trigger

- CHANGELOG.md
Updated CHANGELOG.md for 0.9.0
> Rel: Updated CHANGELOG.md for 0.9.0

- charts/registry/Chart.yaml
- charts/registry/README.md
> Prep: Helm release 0.9.0
